### ISSUE TITLE
如何实现关键词撤回禁言

### ISSUE THREAD

**Issue by lumia1998** [idranme/koishi-plugin-group-manage#1]
设置那只有填关键词
群组平台与群组 ID,没有填写的位置
大佬能提供个示例吗

**Comment by idranme** [comment]
![image](https://github.com/idanran/koishi-plugin-group-manage/assets/96647698/89969d77-531a-463f-b05f-c5e98c468461)

**Comment by lumia1998** [comment]
研究明白了
在规则列表那里点编辑然后
![image](https://github.com/idanran/koishi-plugin-group-manage/assets/63107956/aa1ef33f-a5b6-4192-9341-1fbf5bfc1d88)

**Comment by lumia1998** [comment]
woc  这里能直接编辑啊我说有个   |不知道是啥意思，能改成这一行最后面一个输入框就好了
![image](https://github.com/idanran/koishi-plugin-group-manage/assets/63107956/82ecd292-f05a-4a99-a50e-7fcd6da02d0a)
