### ISSUE TITLE
无声模式

### ISSUE THREAD

**Issue by dingyi222666** [idranme/koishi-plugin-group-manage#3]
希望能增加一个开关，开启后撤回或者禁言某个人不会额外发出消息，不然一下子刷屏太多了（因为我群里很多 bot 有时候会刷屏，这时候插件还是一个个发出消息，也算一种刷屏了）

**Comment by idranme** [comment]
是违禁词检测那一块吗？

**Comment by dingyi222666** [comment]
就是下面这些

![Screenshot_2024-09-01-23-18-47-583_com tencent mobileqq](https://github.com/user-attachments/assets/dfdc64b6-7039-4dc4-9424-237f3c5219d1)

希望这三条消息能设置开关为不发出

**Comment by idranme** [comment]
v1.3.1 已支持

**Comment by idranme** [comment]
![image](https://github.com/user-attachments/assets/fbc8ceb8-a943-426d-82f4-bd0b8538c811)
